import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import './globals.css'
import DesktopNavbar from './components/desktop-navbar'
import MobileNavbar from './components/mobile-navbar'

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800']
})

export const metadata: Metadata = {
  title: 'Your carpentry works',
  description: 'Generated by Tuak '
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      {/* <link
        rel='preload'
        href='/fonts/Monument.otf'
        as='font'
        type='font/otf'
        crossOrigin='anonymous'
      /> */}
      <body className={`${montserrat.className} antialiased`}>
        <DesktopNavbar />
        <MobileNavbar />
        {children}
      </body>
    </html>
  )
}
